### ISSUE TITLE
unfetch/polyfill doesn’t work in webpack 2

### ISSUE THREAD

**Issue by sapegin** [developit/unfetch#31]
When I do:

```js
import 'unfetch/polyfill';
```

I see this error in Safari 10:

> TypeError: fetch is not a function.

Because `fetch` is actually a ES module wrapper:

```js
{__esModule: true, default: function}
```

I suppose it’s because you have `require('.')` in `polyfll.js` and webpack 2 resolves it to `index.es.js`. So this code works for me:

```js
if (!window.fetch) {
    window.fetch = require('unfetch').default;
}
```

I’d be happy to submit a PR but not sure what would be the right fix for this.

**Comment by tunnckoCore** [comment]
that is why i saying for years to not use single dot

**Comment by developit** [comment]
Ah good catch - @sapegin @tunnckoCore, are we good just to change `.` to `unfetch`?

**Comment by sapegin** [comment]
That should be the same, so probably to `./dist/unfetch`.

**Comment by developit** [comment]
Hm - but if someone is using this via webpack 2 the entrypoint would actually be `dist/unfetch.es.js` right?

I just re-read the story here and I actually think we're fine with `.` - that will give people whatever the `package.json` defines as a main field based on their bundler (webpack 2 etc).  The only thing that needs to be done is adding an interop:

```js
if (!window.fetch) {
  window.fetch = (require('unfetch').default || require('unfetch'));
}
```

Seem reasonable?

**Comment by sapegin** [comment]
Yeah, that should work too. Will send a PR.

**Comment by enapupe** [comment]
What do you guys do about `window' not being defined on webpack context? Just define it as an empty obj?

**Comment by enapupe** [comment]
Nevermind. I think my comment is unrelated because I'm talking about server bundling with `target:  node`..

**Comment by developit** [comment]
@enapupe indeed - for that case, are you able to use `isomorphic-unfetch`? It'll use `node-fetch` when bundled/run under node.

**Comment by enapupe** [comment]
Since I don't actually want to polyfill it on node, I ended up doing my own
version of `polyfill.js`:
https://github.com/CheesecakeLabs/fetch/blob/unfetch/src/utils/polyfill.js

It does nothing if window isn't defined.
This works for me because on node I mock fetch with webpack define plugin
at a global level, not as a window prop. And I don't really run `fetch`
calls on ssr as it doesn't really waits for them to complete before
returning the template code. So I just `noop` it.

Thanks for your suggestion anyway.
