### ISSUE TITLE
Rationale behind the headers regex

### ISSUE THREAD

**Issue by deecewan** [developit/unfetch#55]
Just reading through the source and saw the regex. Was wondering if someone could explain the rationale behind it.

For reference, it is (currently) `/^(.*?):\s*([\s\S]*?)$/gm`.

- `/^(.*?):\s*` seems fine
- `[\s\S]` is weird. `\s` is 'any of `\r`, `\n`, `\t`, `\f`, `\v`, ` `'. `\S` is 'any character that *isn't* `\s`'. As far as I can tell, `[\s\S]` is *the same* as `.`.
- `*?` is weird. We're matching to the end of the line. The fewest matches it can take is the same as the largest number. In the scenario it's used in, it's functionally equivalent to `*`, as there can be no more than one end-of-line per line.

I think that the regex could be changed to `/^(.*?):\s*(.*)$/gm` with no functional differences, and a few bytes saved.

Let me know if I've missed anything 😄 .

Edit: Ahh, looks like there is already a [PR open](https://github.com/developit/unfetch/pull/34) that addresses this and some others.

**Comment by mjesun** [comment]
Just for the record, `[\s\S]` is a "universal matching group". The difference with `.` is that `.` is equivalent to `[^\n]`; meaning it matches everything *but* a new line character. But given the fact that the regexp has the `m` flag, they're both the same in this context 🙂

The second `*?` is of course not needed at all, since the first group is already non-greedy, and the second one has to match everything until the end of the line 😀

**Comment by developit** [comment]
PR merged! thanks for catching my regex bugs ;)
