### ISSUE TITLE
Ponyfill acts as a polyfill

### ISSUE THREAD

**Issue by jpike88** [developit/unfetch#77]
Why is this advertised as a ponyfill, when the export line looks for an existing fetch function to bind to? This renders any native implementations non-native, and breaks any libraries looking for that as a marker for feature detection.

https://github.com/developit/unfetch/blob/55560157515dc32b4612daf2653d0300c6ddbe7c/src/index.js#L1

Using this breaks PouchDB on Safari.

https://github.com/pouchdb/pouchdb/issues/7085

**Comment by developit** [comment]
The export uses window.fetch if available, falling back to unfetch's implementation. I think you may be misunderstanding the use of bind()?

**Comment by developit** [comment]
Update: I've realized we are both incorrect here.

Unfetch is not a polyfill, because it doesn't "install" itself as `window.fetch`. It's also not a ponyfill, because it is impure - it will use `window.fetch` if available.

It seems like the issue being encountered here is indirectly a result of the `bind()` usage, rather than solely due to unfetch.  It's because people do this:

```js
window.fetch = require('unfetch');
```

If it were a ponyfill, the above would still break `String(fetch)==[native code` checks, because it would unconditionally assign fetch to the custom implementation.

So it seems like the better fix here would be to still export native fetch when it exists (since the performance is better), but not to bind() it so folks are basically assigning `window.fetch = window.fetch`.

**Comment by developit** [comment]
Fixed in [4.0.0](https://github.com/developit/unfetch/releases/tag/4.0.0)!
