### ISSUE TITLE
Is the typescript definition exported correctly?

### ISSUE THREAD

**Issue by Fnatte** [developit/unfetch#99]
I'm having trouble with unfetch >= 3.1.1. The new TypeScript definition actually broke our build, and I'm not sure how to fix it.

The change was made in PR https://github.com/developit/unfetch/pull/89, in which the default export was removed from `src/index.d.ts`. Was this intentional? The PR is named "Fix _isomorphic-unfetch_ definition" but `packages/isomorphic-unfetch/index.d.ts` is not changed, instead `src/index.d.ts` was changed.

Since `src/index.mjs` export default, shouldn't `src/index.d.ts` also export default?

**Comment by egasimus** [comment]
Same problem with `unfetch@3.0.0` (`webpack@3.12.0`, `ts-loader@2.3.7`, `typescript@2.9.2`):

```
error TS7016: Could not find a declaration file for module 'unfetch'. '/home/user/Edge/Demo/node_modules/unfetch/dist/unfetch.js' implicitly has an 'any' type.
```

**Comment by O4epegb** [comment]
Yep, just updated to v4 and have same issue. Definitions are definitely incorrect.

**Comment by stephenmathieson** [comment]
I believe this is due to TypeScript not respecting the `.mjs` extension.

**Comment by O4epegb** [comment]
Not true, just .d.ts is incorrect.

**Comment by balupton** [comment]
So if you do `import fetch from 'isomorphic-unfetch'` then the types work fine, but it fails to run, due to `TypeError: isomorphic_unfetch_1.default is not a function`

Searching that error, returns the recommendation of doing the following for commonjs modules `import fetch = require('isomorphic-unfetch')` however, then typescript complains there are no types, as the type definition is done with esmodules in mind, not commonjs modules

As such, I've done the following workaround for it:

```
import * as fetchImport from 'isomorphic-unfetch'
const fetch = (fetchImport.default || fetchImport) as typeof fetchImport.default
```

**Comment by samayo** [comment]
Still getting this error. Is there a fix for it?

**Comment by igl** [comment]
> if you do import fetch from 'isomorphic-unfetch' then the types work fine

What am i missing here? there are no types but just a `typeof fetch` which resolves to `any`

![image](https://user-images.githubusercontent.com/293519/87540026-39cc2000-c69f-11ea-9764-ad517fb709b1.png)
